@startuml
left to right direction
actor "Controlador" as fc
rectangle Casa {
  usecase "Fabricante 1" as UC1
  usecase "Fabricante 2" as UC2
  usecase "Fabricante 3" as UC3
  usecase "Fabricante 4" as UC4
} 
fc --> UC1 : Zigbee 
fc --> UC2 : Zigbee 
fc --> UC3 : Z-Wave
fc --> UC4 : Wifi 
@enduml
