# .github/workflows/render-md-mermaid.yml

name: render-md-mermaid

on: push

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Render images for every Mermaid diagram in all Markdown files (*.md) in the repo
        uses: gavioto/render-md-mermaid@v0.1.0-tfg

      - name: Commit rendered png and svg files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*[.svg,.png]"
          commit_message: automatically rendered mermaid diagrams
